# Generated by Django 5.1.15 on 2026-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='magnum_tvk@ukr.net', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+38 073 3 777 333', max_length=32, verbose_name='Телефон')),
                ('address', models.CharField(default='49102, м. Дніпро, вул. Волинська, 46', max_length=255, verbose_name='Адреса')),
                ('address_uk', models.CharField(default='49102, м. Дніпро, вул. Волинська, 46', max_length=255, null=True, verbose_name='Адреса')),
                ('address_en', models.CharField(default='49102, м. Дніпро, вул. Волинська, 46', max_length=255, null=True, verbose_name='Адреса')),
                ('city', models.CharField(default='Дніпро', max_length=100, verbose_name='Місто')),
                ('city_uk', models.CharField(default='Дніпро', max_length=100, null=True, verbose_name='Місто')),
                ('city_en', models.CharField(default='Дніпро', max_length=100, null=True, verbose_name='Місто')),
                ('telegram', models.CharField(blank=True, max_length=255, verbose_name='Telegram')),
                ('viber', models.CharField(blank=True, max_length=32, verbose_name='Viber')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Інформація про компанію',
                'verbose_name_plural': 'Інформація про компанію',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
