# Generated by Django 5.1.15 on 2026-03-07 10:56

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('short_description_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткий опис')),
                ('short_description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Повний опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Повний опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Повний опис')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Головне фото')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул (SKU)')),
                ('brand', models.CharField(default='Magnum', max_length=100, verbose_name='Бренд')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна')),
                ('currency', models.CharField(default='UAH', max_length=10, verbose_name='Валюта')),
                ('availability', models.CharField(choices=[('InStock', 'В наявності'), ('OutOfStock', 'Немає в наявності'), ('PreOrder', 'Під замовлення')], default='InStock', max_length=20, verbose_name='Наявність')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='Meta Description')),
                ('meta_description_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Description')),
                ('meta_description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords')),
                ('meta_keywords_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt текст')),
                ('alt_text_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt текст')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товару',
                'ordering': ['order'],
            },
        ),
    ]
